import { ANSWERS, CORRECT, RED } from "./dataTypes";

export const initialData = {
    [ANSWERS]: [
        {name: 'distinction', answer: ''},
        {name: 'appreciation', answer: ''},
        {name: 'danger', answer: ''},
        {name: 'legs', answer: ''},
        {name: 'hearing' , answer: ''},
        {name: 'eye', answer: ''},
        {name: 'false', answer: ''},
        {name: 'cells', answer: ''},
        {name: 'queen', answer: ''},
        {name: 'drones', answer: ''},
        {name: 'true', answer: ''},
        {name: 'life', answer: ''},
        {name: 'larvas', answer: ''},
        {name: 'queenFood', answer: ''},
        {name: 'varroa', answer: ''},
        {name: 'development', answer:''},
        {name: 'newFamily', answer: ''},
        {name: 'false2', answer: ''},
        {name: 'propolis', answer: ''},
        {name: 'wax', answer: ''}
        ],
    [CORRECT]: [
        {name: 'distinction', answer: 'social-life'},
        {name: 'appreciation', answer: 'pollination-and-honey'},
        {name: 'danger', answer: 'pesticides'},
        {name: 'legs', answer: 'three'},
        {name: 'hearing' , answer: 'in-first-leg'},
        {name: 'eye', answer: 'eye'},
        {name: 'false', answer: 'color-red'},
        {name: 'cells', answer: 'hexagon'},
        {name: 'queen', answer: 'laying-eggs'},
        {name: 'drones', answer: 'nothing'},
        {name: 'true', answer: 'guardians'},
        {name: 'life', answer: 'six-weeks'},
        {name: 'larvas', answer: 'feeder-bees'},
        {name: 'queenFood', answer: 'milk'},
        {name: 'varroa', answer: 'pest'},
        {name: 'development', answer:'spring'},
        {name: 'newFamily', answer: 'division'},
        {name: 'false2', answer: 'crystal'},
        {name: 'propolis', answer: 'resin'},
        {name: 'wax', answer: 'cosmetics-and-candles'}

    ],
    [RED]: [
        {answer: 'lonely-life', color: ''},
        {answer: 'pollination', color: ''},
        {answer: 'battle-with-pests', color: ''},
        {answer: 'reduction-wild-pollinators', color: ''},
        {answer: 'wild-pollinators', color: ''},
        {answer: 'poisonous-plants', color: ''},
        {answer: 'two', color: ''},
        {answer: 'four', color: ''},
        {answer: 'in-head', color: ''},
        {answer: 'in-abdomen', color: ''},
        {answer: 'sensili', color: ''},
        {answer: 'antennae', color: ''},
        {answer: 'ultraviolet', color: ''},
        {answer: 'small-parts', color: ''},
        {answer: 'pentagon', color: ''},
        {answer: 'octagon', color: ''},
        {answer: 'defense', color: ''},
        {answer: 'food-dispensation', color: ''},
        {answer: 'getting-food', color: ''},
        {answer: 'defense2', color: ''},
        {answer: '10-km', color: ''},
        {answer: 'new-born', color: ''},
        {answer: 'one-year', color: ''},
        {answer: 'five-years', color: ''},
        {answer: 'queen', color: ''},
        {answer: 'flying-bees', color: ''},
        {answer: 'honey', color: ''},
        {answer: 'pollen-and-milk', color: ''},
        {answer: 'larva', color: ''},
        {answer: 'locator', color: ''},
        {answer: 'summer', color: ''},
        {answer: 'autumn', color: ''},
        {answer: 'mating', color: ''},
        {answer: 'moving', color: ''},
        {answer: 'antibacterial-honey', color: ''},
        {answer: 'bee-milk', color: ''},
        {answer: 'fluid-from-leaves', color: ''},
        {answer: 'wax', color: ''},
        {answer: 'kitchen', color: ''},
        {answer: 'cleaning', color: ''},
    ]

}
